// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2o57-N9LYM_I9sxhsPXDez6SQkOt8y0A',
    appId: '1:441185724649:ios:22a76b939681196c34e878',
    messagingSenderId: '441185724649',
    projectId: 'fema-b608b',
    storageBucket: 'fema-b608b.firebasestorage.app',
    iosBundleId: 'com.fema.fema',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcpldTXOVwtIHEzw90WwmnajFmXS8E5Ys',
    appId: '1:441185724649:web:95068cda2b570b2d34e878',
    messagingSenderId: '441185724649',
    projectId: 'fema-b608b',
    authDomain: 'fema-b608b.firebaseapp.com',
    storageBucket: 'fema-b608b.firebasestorage.app',
    measurementId: 'G-VFBQ7NZVKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5j3y14cvYlLpfKj0mzVMTGjFY8RQtDQ',
    appId: '1:441185724649:android:cb7bbd032ad79c7534e878',
    messagingSenderId: '441185724649',
    projectId: 'fema-b608b',
    storageBucket: 'fema-b608b.firebasestorage.app',
  );
}
